import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";


import Image from "next/image";


import About from "../components/About";
import Skills from "../components/Skills";


import Nav from "../components/Nav";
import Link from "next/link";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portofolio | SovTech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <br></br>
      <br></br> <br></br>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl dark:text-blue-500">SovTech</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Kyle Padayachee
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            I am a driven South African Indian professional with experience in the Manufacturing and 
Business fields and keen interest in Software Development. I am extremely hardworking, 
motivated, organized and dependable. I wish to expand my career by developing new skills
as well as contributing ideas to potential employers. I am a strong believer in teamwork, have 
a passion for quality, solid planning skills and strong analytical abilities I am committed to 
continuous improvement and am always willing to learn and grow.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <Link href="https://www.linkedin.com/in/kyle-padayachee/">
                <AiFillLinkedin />
              </Link>
              
              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Image src='/../public/assets/cover-photo.jpg' layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        
        <About/>
        <br></br>
        <br></br>
      
        
        <Skills/>
        
        <section className="py-10">
          <div id="portfolio">
            <h3 className="text-3xl py-1 dark:text-white ">Github Profile</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
             Please feel free to have a look at my projects that I have created and worked
             with talented people to showcase my development skills and creativity.

            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
               I look forward to collaborating with you at Sovtech Technologies
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
           

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-xl hover:opacity-10"
                width={"100%"}
                height={"100%"}
                layout="responsive"
            
              />
              
              <span className="text-teal-500"><Link href="https://github.com/kyl88">Click Here To Access my GitHub Account</Link> </span>
            </div>
          
         
          </div>
        </section>
      </main>
      <footer >
        <a
          href="https://www.sovtech.co.za/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright 2022{' '}
          <span >
            <Image  src="/../public/assets/SovTech-Small.png" alt="SovTech" width="75" height="16"/>
          </span>
        </a>
      </footer>
    </div>
    
  );
}